sudo: required
dist: trusty
language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mingw-w64 mingw32

script:
  - make sslscan CC=clang
  - make sslscan CC=gcc
  # OpenSSL can't be compiled out-of-the box with clang, see
  # http://wiki.openssl.org/index.php/Compilation_and_Installation#Modifying_Build_Settings
  #- make static CC=clang
  - make static CC=gcc
  - make -f Makefile.mingw
  - make -f Makefile.mingw BUILD_32BIT=1
